spring:
  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 6379
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
  datasource:
    url: jdbc:postgresql://localhost:5433/demo
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: public
        jdbc:
          lob:
            non_contextual_creation: true
  sql:
    init:
      mode: never
jwt:
  secret: mKxGBnviS6zp8bA7VPMjq7G2rMEbGExBHW6yWhXieGpMUwJHhdRL8U7Ug2eZPS9s1tARlEjUZPRm5UHygXqtKIivvD2ld+2AXAv9DWbuY2ofFP9pNVkcaBrpdPW7bM1PnBqjaKrKfAYVPmtfohXm7YatrAZvAP9JofaEfWUx/Jfd1AnaCNFQ4kgrdDtqWQFRdFAzbl+vuMPSqe/wqXOZUdWx3C5T4AEYT2Gq0nyrh7K3XNZMN2+p6AeLKZ4hr9hvA9z6CQfEmZHi8IyW1hKFReWvzPgSeYRcKVh7YOgGkJNEm6shjZmWy6/xdiufGt4SpWx3zBLq2x5GIwziKW7oeA==

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  info:
    title: Demo API
    version: 1.0.0
  api-docs:
    enabled: true
    path: /v3/api-docs