CREATE TABLE IF NOT EXISTS users (
    id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    name VARCHAR(500) NOT NULL,
    date_of_birth VARCHAR(10) NOT NULL CHECK (date_of_birth ~ '^\d{2}\.\d{2}\.\d{4}$'),
    password VARCHAR(500) NOT NULL CHECK (LENGTH(password) >= 8)
);

CREATE TABLE IF NOT EXISTS accounts (
    id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    user_id BIGINT NOT NULL UNIQUE REFERENCES users(id),
    balance DECIMAL(19,2) NOT NULL CHECK (balance >= 0),
    initial_deposit DECIMAL(19,2) NOT NULL
);

CREATE TABLE IF NOT EXISTS email_data (
    id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    user_id BIGINT NOT NULL REFERENCES users(id),
    email VARCHAR(200) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS phone_data (
    id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    user_id BIGINT NOT NULL REFERENCES users(id),
    phone VARCHAR(13) NOT NULL UNIQUE CHECK (phone ~ '^7\d{10}$')
);